micronaut:
  application:
    name: jsonVersionFileSystem
  server:
    port: 8081
    context-path: /jsonVersionFileSystem
    cors:
      enabled: true
  config-client:
    enabled: true
  session:
    http:
      cookie: true
      header: true


json:
  file:
    location: C:\\JsonVersionFileDemo

